### PR TITLE
Log vision values when taking shot

### PR DESCRIPTION
**Pull request by james-ward**

### CODE REVIEW

**Comment by auscompgeek** [comment]
Since these are on NetworkTables, I believe these are captured by default by DataLogManager.

If others think it'll be helpful I'm fine with the extra logging, but we'll probably be able to find these values in the log without much work.

**Comment by james-ward** [comment]
I think the real value is in having these recorded in a way where we can tell when we have taken a shot, rather than having to filter them out of all the other records.

**Comment by auscompgeek** [comment]
I suppose that is useful. Would this be more useful then if we also log how old those vision values are when the shot is taken?

**Comment by james-ward** [comment]
Maybe, although the fact that the vision is valid and pointing in vaguely the right direction is what I am more interested in. I couldn't see a quick way to do something like that, so I left it in the too-hard basket. It's not necessary.

We really care about it taking a shot when the vision is clearly showing that the target isn't in front of the turret.

**Review by OliverW10 — APPROVED** [review]

**Pull request merged**
